### ISSUE TITLE
博主你有做导入训练好的模型在实际任务如分类的例子的演示吗

### ISSUE THREAD

**Issue by ares5221** [fennuDetudou/BERT_implement#2]

**Comment by Biaocsu** [comment]
@ares5221  你好，我正好最近就在做利用训练好的模型对一个一个文本进行预测，然后预测速度超级慢，文本比较长，平均2000千字左右吧，平均每个txt文本需要30s，都快崩溃，肯定是出问题了，但又找不出原因，请问你后面做的是怎样的一个速度？（我使用Pytorch版本预测，在GPU上同样的数据平均每个0.3s，CPU上1.7s）

**Comment by fennuDetudou** [comment]
这个项目已经好久不维护了，实际的例子可以看另一个仓库里的东西

**Comment by ares5221** [comment]
> 是怎样的一个速度？（我

我原来试过对长语句预测，速度也是很慢，现在已经将语句分成较短的句子来处理，用的tf，
